### PR TITLE
Remove '0% funded' bar for now

### PR DESCRIPTION
**Pull request by benjaoming**

### CODE REVIEW

**Comment by jamalex** [comment]
Tests? Screenshots? DOCUMENTATION? ;)

Thanks!

**Comment by benjaoming** [comment]
Well, this is the state of the current site:

screenshot from 2016-07-28 00 53 27

...I didn't run the site locally or test it :)

**Comment by jamalex** [comment]
Yeah, I was kidding -- we don't have the same PR standards on this site as we do on the apps. :)

I'll deploy to the staging server and we can make sure it looks ok there.

**Comment by benjaoming** [comment]
Maybe @whitzhu can have a look since now there's a problem with the video size -> http://flestaging.learningequality.org/kolibri/

**Comment by whitzhu** [comment]
@66eli77 do you taking a look at the video size?

**Comment by 66eli77** [comment]
sure, I will take at look

**Comment by 66eli77** [comment]
fixed here https://github.com/fle-internal/fle-home/pull/308
browserstack tested on IE9 and firebox 43

**Comment by benjaoming** [comment]
@66eli77 sounds good, but is it deployed? It's still saying '0% funded' here: https://learningequality.org/kolibri/

**Comment by 66eli77** [comment]
only @jamalex can deploy it.

**Pull request merged**
