### PR TITLE
Mobile video

### PR DESCRIPTION
**Pull request by jtamiace**
replaces video on landing screen and makes everything above the fold responsive.

### CODE REVIEW

**Comment by 66eli77** [comment]
I notice the sticky bar's not sticky anymore, is that intentional? Also the igg progress bar point mark doesn't point at the right percentage on mobile. I'm the one to blame at, the progress bar's code isn't very flexible

**Comment by jamalex** [comment]
@66eli77 Yes, we didn't see a need to have it be sticky -- doesn't need to show after they scroll down. And I think @jtamiace was doing a simpler version of the progress bar for mobile, since there were issues.

**Comment by jamalex** [comment]
The one thing that would be useful to have sticky would be a link to the "Donate" page.

**Comment by 66eli77** [comment]
I can fix the progress bar for mobile.
how about no sticky on mobile, but sticky on desktop?

**Comment by jamalex** [comment]
Why sticky? Once they're reading about Kolibri itself, I don't see much need for seeing the progress bar. Unless there's a "donate" link right in the sticky bar as well?

**Comment by 66eli77** [comment]
Ok, no sticky, I don't like the idea to put the donate button on sticky bar, any buttons on such place feel untrustworthy, that's where the ads lives haha

**Pull request merged**
