### PR TITLE
updated timeline, added animate.css and wow.js

### PR DESCRIPTION
**Pull request by whitzhu**
@jtamiace can you review my code

### CODE REVIEW

**Comment by aronasorman** [comment]
> Files Changed (4,910)

Only our design lead can take on such a herculean task.

**Comment by jtamiace** [comment]
much libraries

**Comment by jtamiace** [comment]
wait, @whitzhu, neither js libraries nor timeline changes are in here (or maybe it is but the PR is too big to show). looks like your entire virtual environment folder has been included in this PR (hence the size). can you add ENV/* to the list in your .gitignore file, commit that change, and then push again to your repo?

@aronasorman would she need to make another PR or will this one update accordingly?

**Comment by aronasorman** [comment]
@jtamiace it probably isn't loading.

@whitzhu I'd rather have this PR closed, and then start from a complete fresh branch. Continuing this PR would mean that these 4,910 objects will be recorded in the git history and would thus bloat this repo. You can try either just copying the files you edited over or just start from scratch, if they're easy to reproduce.

**Comment by jtamiace** [comment]
TIL

**Pull request closed without merging**
