### PR TITLE
modular quote section

### PR DESCRIPTION
**Pull request by 66eli77**

### CODE REVIEW

**Comment by jtamiace** [comment]
lookin good

**Comment by jamalex** [comment]
Might be good to use a quote mark that's less than 13KB? https://github.com/66eli77/fle-home/blob/f94374d99c23b0f127fbd843b2e758d361fdd25c/fle_site/apps/main/static/img/kickstarter/quote/quote.png

**Comment by jtamiace** [comment]
@66eli77 testing it on my side, might be good to allow them to pause the video too

**Comment by 66eli77** [comment]
@jamalex will optimize all the image assets at the very end
@jtamiace will add pause in later PR

**Pull request merged**
