### PR TITLE
new images for bridge section and improved amount of white space on page

### PR DESCRIPTION
**Pull request by jtamiace**

### CODE REVIEW

**Comment by jtamiace** [comment]
deleted!

**Comment by aronasorman** [comment]
@jamalex can you redeploy the new FLE home?

**Comment by jtamiace** [comment]
(celebrates!)


Respectfully,

Jessica Aceret
UCSD Undergraduate
B.S. Cognitive Science - Human Computer Interaction
B.A. Sociology - Science and Medicine

**Comment by aronasorman** [comment]
:dancers:

**Comment by jamalex** [comment]
Deployed to http://flestaging.learningequality.org/, and it looks good, so going live now!

**Comment by jamalex** [comment]
And LIVE! Beautiful: https://learningequality.org/

**Pull request merged**
